### ISSUE TITLE
The document could not be saved. 

### ISSUE THREAD

**Issue by ivanoterouvigo** [ONLYOFFICE/docker-onlyoffice-owncloud#10]
**The document could not be saved.** 
Please check your connection settings or contact your administrator. When you click the OK button, you will be prompted to download the document. Find more information about the Document Server connection.

![docker_error_002](https://user-images.githubusercontent.com/11814769/31386141-13b26568-adc6-11e7-9df2-81aea0ec8e16.png)

**What do I need to do?**

**Comment by ivanoterouvigo** [comment]
Well sorry again.

I review me configuration, and I set.

StorageUrl to new IP.

**Comment by LinneyS** [comment]
Working?
I close the issue?

**Comment by ivanoterouvigo** [comment]
Yes of course, sorry
