### ISSUE TITLE
New document copied from documents created in NC has no content

### ISSUE THREAD

**Issue by nathchan** [ONLYOFFICE/docker-onlyoffice-owncloud#15]
Original File created from nextcloud
![image](https://user-images.githubusercontent.com/10007388/37697467-a353d3be-2d0f-11e8-8bab-be629c7fa3e2.png)

New file copied using nextcloud to new folder has no content
![image](https://user-images.githubusercontent.com/10007388/37697660-a73514e2-2d10-11e8-98b2-7bffc5d0b86a.png)

**Comment by LinneyS** [comment]
It's must be fixed on next release
https://github.com/ONLYOFFICE/onlyoffice-owncloud/commit/f965c275e20bb72d25c9c1ad48b9a7d1dc6d355f
