### ISSUE TITLE
Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.)

### ISSUE THREAD

**Issue by kareller** [ONLYOFFICE/docker-onlyoffice-owncloud#29]
I have a problem between owncloud and onlyoffice, please check screenshots. I tried lots of things but problem is continue.

Do you have any suggestion to fix this error?

"Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.)"

Thanks for advice.

Onlyoffice is working on docker;

![53695473-38ad9200-3dcd-11e9-81b0-b699dd219bf6](https://user-images.githubusercontent.com/25711592/53699727-82fa3780-3dfc-11e9-86c3-44c36e0e5fbd.png)

ownCloud;

![screenshot_1](https://user-images.githubusercontent.com/25711592/53699732-87265500-3dfc-11e9-87a2-89b5bfc98dcf.png)

**Comment by alexanderonlyoffice** [comment]
Hello @kareller, if the issue still relevant, please try to disable 'Advanced server settings' section and click on the 'Save' button. If you Document Server and ownCloud can access each other it should work. The error you get means that the Document Server cannot download the file from ownCloud. In case you want to use internal addresses, you need to specify the address of your ownCloud in the field 'Server address for internal requests from the Document Editing Service'

Check the accessibility of the servers to each other, please do the following: 
- on the server with Document Server, enter the container with a command sudo docker exec -it [container_id] bash and execute the command `wget https://owncloud_address/` from inside the container;
- on the server with ownCloud execute `wget https://documentserver_address/`

**Comment by kareller** [comment]
Thank you @alexanderonlyoffice I already fixed problem.
