### ISSUE TITLE
Error while downloading the document file to be converted.

### ISSUE THREAD

**Issue by RebelUkraine** [ONLYOFFICE/docker-onlyoffice-owncloud#36]
I've installed owncloud, and run Docker image ONLYOFFICE
I got correct https://my.owncloud.host:docker-port/welcome/
but when I try set onlyoffice settings in owncloud panel, I got "Error while downloading the document file to be converted."
I search about 6 hours this problem, and make all advises but it still do not work
And I see that inside container I can't resolve owncloud host
wget: unable to resolve host address ‘my.owncloud.host’
I'm using one SSL Let'sEncrypt serts on both
Running docker image by
 `docker run -i -t -d -p 8443:443     -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data  onlyoffice/documentserver`
enabled SSL3 in docker 
```
root@d54f96f3bd8c:/# openssl s_client -ssl3 -connect 172.17.0.2:443
139969868351128:error:140A90C4:SSL routines:SSL_CTX_new:null ssl method passed:ssl_lib.c:1878:
```
set up
`'onlyoffice' => array ( 'verify_peer_off' => true, ),`
in the owncloud config
and 
`"rejectUnauthorized": false`
in /etc/onlyoffice/documentserver/default.json

**Comment by CarlOnlyoffice** [comment]
Hello @RebelUkraine 
First you have to make sure that the domain name of your ownCloud can be resolved from the Document Server container. As a workaround, try to add the pair IP/domain of your ownCloud to /etc/hosts in the container.

**Comment by RebelUkraine** [comment]
now it resolving
```
root@aed32e1dfcb2:/# wget https://cloud.rockwill-wealth.co.uk/
--2019-12-03 11:29:38--  https://cloud.rockwill-wealth.co.uk/
Resolving cloud.rockwill-wealth.co.uk (cloud.rockwill-wealth.co.uk)... 172.17.0.1
Connecting to cloud.rockwill-wealth.co.uk (cloud.rockwill-wealth.co.uk)|172.17.0.1|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cloud.rockwill-wealth.co.uk/index.php/login [following]
--2019-12-03 11:29:38--  https://cloud.rockwill-wealth.co.uk/index.php/login
Reusing existing connection to cloud.rockwill-wealth.co.uk:443.
HTTP request sent, awaiting response... 200 OK
Length: 10565 (10K) [text/html]
Saving to: ‘index.html’

index.html          100%[===================>]  10.32K  --.-KB/s    in 0s

2019-12-03 11:29:38 (67.7 MB/s) - ‘index.html’ saved [10565/10565]
```

**Comment by CarlOnlyoffice** [comment]
@RebelUkraine 
Please check the log /var/log/onlyoffice/documentserver/converter/out.log inside the container. What errors do you see there?

**Comment by RebelUkraine** [comment]
[2019-12-03T11:36:37.933] [ERROR] nodeJS - error downloadFile:url=https://my.owncloud.host:8443/index.php/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiL                                                                                                                                                             CJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.ZVm9UStcfWPVJy3AdjWAB3Oo2ntLh-f7OaN                                                                                                                                                             k0eJSI4U;attempt=3;code:null;connect:null;(id=conv_check_534095589_docx)
Error: Error response: statusCode:404 ;body:
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /index.php/apps/onlyoffice/empty</pre>
</body>
</html>

**Comment by RebelUkraine** [comment]
Holy scripts!!!!! I Think found my problem!!!
In setup of onlyoffice in owncloud panel, i set additiobal setting. But when i removed additional settings, all is start working.
Thanx for your response  @CarlOnlyoffice

**Comment by CarlOnlyoffice** [comment]
@RebelUkraine 
Glad you have found the reason of the issue.
