### ISSUE TITLE
PostgreSQL usage unavailable

### ISSUE THREAD

**Issue by Ivan-Igorevich** [ONLYOFFICE/docker-onlyoffice-owncloud#44]
Hello, i try to use an option of postgresql as i set up an admin account, but an application returns "unable to connect". Of course i installed DBeaver and connected to my localhost successfully... what am i doing wrong while installation, or maybe there's a problem in my docker-compose file? but i'm sure to download it from this repository... i attach some screenshots to show what i get from this situation
![Screenshot from 2020-03-26 21-22-00](https://user-images.githubusercontent.com/12792352/77683305-3f471280-6fa9-11ea-85e6-5e54ad48ed15.png)
![screenshot_1](https://user-images.githubusercontent.com/12792352/77683290-38b89b00-6fa9-11ea-8a39-6e41c9c44cb2.png)
![screenshot_2](https://user-images.githubusercontent.com/12792352/77683493-846b4480-6fa9-11ea-903e-34a12be1eaf1.png)

**Comment by HelenBelova17** [comment]
Hello @**Ivan-Igorevich**, by default, this container uses SQLite for data storage if you want to use another go to https://github.com/nextcloud/docker for settings.

**Comment by Ivan-Igorevich** [comment]
and all the app- or db- related issues should be addressed to `nextcloud`?
