### ISSUE TITLE
You are accessing the server from an insecure domain.

### ISSUE THREAD

**Issue by ivanoterouvigo** [ONLYOFFICE/docker-onlyoffice-owncloud#9]
**You are accessing the server from an insecure domain.**
Contact your administrator. If you are the administrator, configure "trusted_domains" in config / config.php. In config / config.sample.php you will find an example for the configuration.

My public IP is: http://193.145.246.20/

![docker_config_001](https://user-images.githubusercontent.com/11814769/31384412-313b5cea-adbf-11e7-8e4a-eb90541741c3.png)

![docker_config_003](https://user-images.githubusercontent.com/11814769/31384556-c6ce3fd4-adbf-11e7-99d8-5da53aa6edb1.png)

**What do you think it is the best way to do it working well?**

Thanks and best regards

**Comment by LinneyS** [comment]
Hello @ivanoterouvigo 

To complete step 4 of the [installation](https://github.com/ONLYOFFICE/docker-onlyoffice-owncloud#installation), did you go through the ownCloud wizard at **http://10.145.246.170** ? ownCloud was automatically added to the _trusted_domain_ list of the config.
In step 5 of the installation, we added the **nginx-server** address to the _trusted_domain_ list of the config.

Now, are you trying to login to ownCloud from the unregistered address **http://193.145.246.20** ? So add it to the list, as indicated in the message.

What is your question to us?

**Comment by ivanoterouvigo** [comment]
Thank you @LinneyS 

I checked several post and finally I do it well.

I follow this post.
https://central.owncloud.org/t/problem-with-trusted-domains/6544

It work fine now.

I only change 10.145.246.170 to new IP.

Thanks
